###
GET http://localhost:5295

###
GET http://localhost:5295/tasks

###
GET http://localhost:5295/tasks/1

###
POST http://localhost:5295/tasks
Content-Type: application/json

{
  "name": "掃除",
  "taskTypeId": 1
}

###
PUT http://localhost:5295/tasks/1
Content-Type: application/json

{
  "name": "掃除2",
  "taskTypeId": 1
}

###
DELETE http://localhost:5295/tasks/1